"""Fase 7: agrega columnas de 2FA/TOTP a users

Revision ID: dd3e6766ea93
Revises: 25c3d03285ea
Create Date: 2026-08-23 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd3e6766ea93'
down_revision = '25c3d03285ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('backup_codes', sa.Text(), nullable=True))

    # server_default solo hacía falta para completar la columna NOT NULL en
    # las filas ya existentes; no queremos que quede fijo en el esquema (el
    # modelo pone el default en el lado de la aplicación, no de la base de
    # datos), así que se retira una vez aplicada la migración.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret_encrypted')
    # ### end Alembic commands ###
