"""verificacion de email

Revision ID: f49c8217e4fc
Revises: d2fb8b36a077
Create Date: 2026-08-29 16:36:54.061443

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f49c8217e4fc'
down_revision = 'd2fb8b36a077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default solo para completar la columna NOT NULL en las
        # filas ya existentes (mismo criterio que totp_enabled en
        # dd3e6766ea93) -- el default real vive del lado de la aplicación
        # (app/models.py), no del esquema, así que se retira después.
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_verify_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email_verify_token'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_verify_token_expires_at')
        batch_op.drop_column('email_verify_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
